[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "REPLACE_WITH_MNEMONIC_FROM_ENV"
derivation = "m/44'/5757'/0'/0/0"

